name: CI/CD Pipeline

# Trigger the workflow on push to the 'main' branch
on:
  push:
    branches:
      - main

# Define the jobs in the workflow
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true # Ensures submodules are retrieved if present

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      # Add debugging: Print environment variables
      - name: Debug Environment
        run: env

      # Add debugging: List files before installing dependencies
      - name: List files
        run: ls -la

      # Check for package-lock.json
      - name: Check for package-lock.json
        run: |
          if [ ! -f package-lock.json ]; then
            echo "Error: package-lock.json is missing!"
            exit 1
          fi

      # Install dependencies
      - name: Install dependencies
        run: |
          npm cache clean --force # Clears npm cache to avoid stale data
          npm install

      # Run tests
      - name: Run tests
        run: npm test

  deploy:
    # The deploy job depends on the build-and-test job
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy step (replace with actual deployment commands)
      - name: Deploy to Production
        run: |
          echo "Deploying application..."
          # Replace with actual deployment commands
          npm run deploy

